### PR TITLE
feat(dark-mode): implement basic dark mode

### PR DESCRIPTION
**Pull request by colinaaa**
New features:

* auto detect by media query
* manual switch between light and dark mode

Known issues:

- [x] bad color displaying in dark mode

图片

- [x] all the buttons shifted to left

图片

I will try some new colors, suggestions are appreciated.

### CODE REVIEW

**Comment by winderica** [comment]
好！
才发现你不在 @UniqueStudio/web ，等下找人拉你进来

**Comment by colinaaa** [comment]
Modifications:

* remove secondary in theme and directly set background color in the theme.
* use contained button instead of text button.

Preview:

* Login

image

* Dashboard

image

* Candidate

image

**Comment by fredliang44** [comment]
> 好！
> 才发现你不在 @UniqueStudio/web ，等下找人拉你进来

Done

**Comment by ManiaciaChao** [comment]
should merge this PR A.S.A.P.

**Pull request merged**
